#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -g $(whoami))
if   [ $STYXGROUP = "501" ]; then
  fg_reboot
elif [ $STYXGROUP = "502" ]; then
  ts_reboot
elif [ $STYXGROUP = "503" ]; then
  ks_reboot
elif [ $STYXGROUP = "504" ]; then
  tv_reboot
elif [ $STYXGROUP = "505" ]; then
  sd_reboot
else echo "Group not does exit";
fi
