#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -nG)
if   [[ "$STYXGROUP" == *"televinken"* ]]; then
  tv_reboot
elif [[ "$STYXGROUP" == *"kundservice"* ]]; then
  3ks_reboot
elif [[ "$STYXGROUP" == *"telesales"* ]]; then
  3ts_reboot
elif [[ "$STYXGROUP" == *"solsidan"* ]]; then
  3sd_reboot
else echo "Group not does exist";
fi
echo $USER
