#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -nG)
if   [[ "$STYXGROUP" == *"televinken"* ]]; then
  tv_taskrunner
elif [[ "$STYXGROUP" == *"kundservice"* ]]; then
  3ks_taskrunner
elif [[ "$STYXGROUP" == *"telesales"* ]]; then
  3ts_taskrunner
elif [[ "$STYXGROUP" == *"solsidan"* ]]; then
  3sd_taskrunner
else echo "Group not does exist";
fi
echo $USER