#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -g $(whoami))
if   [ $STYXGROUP = "501" ]; then
  fg_taskrunner
elif [ $STYXGROUP = "502" ]; then
  ts_taskrunner
elif [ $STYXGROUP = "503" ]; then
  ks_taskrunner
elif [ $STYXGROUP = "504" ]; then
  tv_taskrunner
elif [ $STYXGROUP = "505" ]; then
  sd_taskrunner
else echo "Group not does exit";
fi
