#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -nG)
if   [[ "$STYXGROUP" == *"televinken"* ]]; then
  tv_login
elif [[ "$STYXGROUP" == *"kundservice"* ]]; then
  3ks_login
elif [[ "$STYXGROUP" == *"telesales"* ]]; then
  3ts_login
elif [[ "$STYXGROUP" == *"solsidan"* ]]; then
  3sd_login
else echo "Group not does exist";
fi
echo $USER
