#!/bin/bash

source /usr/local/bin/styx/lib/styx-functions

STYXGROUP=$(id -g $(whoami))
if   [ $STYXGROUP = "501" ]; then
  fg_exit
elif [ $STYXGROUP = "502" ]; then
  ts_exit
elif [ $STYXGROUP = "503" ]; then
  ks_exit
elif [ $STYXGROUP = "504" ]; then
  tv_exit
elif [ $STYXGROUP = "505" ]; then
  sd_exit
else echo "Group not does exist";
fi
